<a href="https://colab.research.google.com/github/puttipongyy/python_dataviz2023/blob/main/Final_dataviz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dasboard
[ข้อความลิงก์](https://lookerstudio.google.com/u/0/reporting/aa0c6d4c-36b4-42be-a961-45994bacfee1?fbclid=IwAR1H8wV-5K8YP2S1Dx4OmvGxZl6nEkgRryh4qbNtG-FeBLIOev-OwNvf3Z0)

รายชื่อสมาชิก
- จิรภัทร กาญจนวนา 633020368-1
- นางสาวลภัสรดา แดงสูงเนิน 643020518-9
- นายศิริโชค ศิริวิชา 643020522-8
- นายธนาธิป อินทรคีรี 643021265-7
- นางสาวธิติพร ใจเอื้อ 643021266-5
- พุทธิพงศ์ ยางนอก 643021268-1

#สิ่งที่ต้องการแสดงใน dashboard

- กราฟเวลา 3 ช่วง
            ช่วงที่ 1 : 2017/12/07 - 2017/12/19
            ช่วงที่ 2 : 2019/02/13 - 2019/02/26
            ช่วงที่ 3 : 2019/03/28 - 2019/04/10
- แสดงยอดขายของแต่ละช่วง
- สัดส่วนรูปแบบการชำระเงิน

In [450]:
import pandas as pd

In [451]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#เชื่อม ตำแหน่งของโฟลเดอร์ไดรฟ

In [452]:
import os
os.chdir('/content/drive/MyDrive/Dataviz_Final_thana')
!pwd #เช็ค path ที่กำลังทำงานอยู่

/content/drive/MyDrive/Dataviz_Final_thana

In [453]:
!ls

Final2023_DataViz  transactions_with_Payment.csv     ts3_test_out.csv
operator.csv	   transactions_with_Payment.gsheet
transactions.csv   transactions_with_Time.csv

#อ่านไฟล์ข้อมูล

In [454]:
#op1 = pd.read_csv('POS_operator_logs_20171207-20171219.csv')
#op2 = pd.read_csv('POS_operator_logs_20190213-20190226.csv')
#op3 = pd.read_csv('POS_operator_logs_20190328-20190410.csv')
#ts1 =  pd.read_csv('POS_transactions_20171207-20171219.csv')
#ts2 =  pd.read_csv('POS_transactions_20190213-20190226.csv')
#ts3 =  pd.read_csv('POS_transactions_20190328-20190410.csv')

#กำหนดการอ่านไฟล์ว่าจะให้เป็นข้อมูลประเภทอะไร

In [455]:
types_dict = {'WorkstationGroupID': str, 'TranID' : str,  'BeginDateTime' : str , 'EndDateTime' : str,  'OperatorID' :  int, 'TranTime' : int, 'BreakTime' : int, 'ArtNum' : int
              , 'TNcash' : bool, 'TNcard' : bool,  'Amount' : float }

In [456]:
op1 = pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_operator_logs_20171207-20171219.csv' ,dtype = str)
op2 = pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_operator_logs_20190213-20190226.csv', dtype = str)
op3 = pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_operator_logs_20190328-20190410.csv', dtype = str)
ts1 =  pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_transactions_20171207-20171219.csv', dtype = types_dict  )
ts2 =  pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_transactions_20190213-20190226.csv', dtype = types_dict )
ts3 =  pd.read_csv('/content/drive/MyDrive/Dataviz_Final_thana/Final2023_DataViz/POS_transactions_20190328-20190410.csv', dtype = types_dict )

# ตรวจสอบข้อมูล

In [457]:
ts1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66863 entries, 0 to 66862
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  66863 non-null  object
 1   TranID              66863 non-null  object
 2   BeginDateTime       66863 non-null  object
 3   EndDateTime         66863 non-null  object
 4   OperatorID          66863 non-null  int64
 5   TranTime            66863 non-null  int64
 6   BreakTime           66863 non-null  int64
 7   ArtNum              66863 non-null  int64
 8   TNcash              66863 non-null  bool
 9   TNcard              66863 non-null  bool
 10  Amount              66863 non-null  float64
dtypes: bool(2), float64(1), int64(4), object(4)
memory usage: 4.7+ MB

In [459]:
op1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4708 entries, 0 to 4707
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  4708 non-null   object
 1   WorkstationID       4708 non-null   object
 2   TranID              4708 non-null   object
 3   BeginDateTime       4708 non-null   object
 4   OperatorID          4708 non-null   object
 5   Items               4708 non-null   object
dtypes: object(6)
memory usage: 220.8+ KB

In [460]:
op1.describe()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
count,4708,4708,4708,4708,4708,4708
unique,2,22,4708,4682,48,4
top,1,21,1712071060162,2017-12-09T14:58:02,10,OperatorSignOn
freq,4520,546,1,2,548,1264

In [461]:
op1.head()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn

In [462]:
op2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5218 entries, 0 to 5217
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  5218 non-null   object
 1   WorkstationID       5218 non-null   object
 2   TranID              5218 non-null   object
 3   BeginDateTime       5218 non-null   object
 4   OperatorID          5218 non-null   object
 5   Items               5218 non-null   object
dtypes: object(6)
memory usage: 244.7+ KB

In [463]:
op2.describe()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
count,5218,5218,5218,5218,5218,5218
unique,2,19,5211,5186,45,4
top,1,4,190226106022155,2019-02-13T05:37:55,10,OperatorLock
freq,5100,1134,2,2,518,1463

In [464]:
op3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4178 entries, 0 to 4177
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  4178 non-null   object
 1   WorkstationID       4178 non-null   object
 2   TranID              4178 non-null   object
 3   BeginDateTime       4178 non-null   object
 4   OperatorID          4178 non-null   object
 5   Items               4178 non-null   object
dtypes: object(6)
memory usage: 196.0+ KB

In [465]:
op3.describe()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
count,4178,4178,4178,4178,4178,4178
unique,2,18,4155,4163,50,4
top,1,4,1904101060172,2019-03-29T18:05:36,10,OperatorSignOn
freq,4044,630,2,2,500,1080

In [466]:
ts1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66863 entries, 0 to 66862
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  66863 non-null  object
 1   TranID              66863 non-null  object
 2   BeginDateTime       66863 non-null  object
 3   EndDateTime         66863 non-null  object
 4   OperatorID          66863 non-null  int64
 5   TranTime            66863 non-null  int64
 6   BreakTime           66863 non-null  int64
 7   ArtNum              66863 non-null  int64
 8   TNcash              66863 non-null  bool
 9   TNcard              66863 non-null  bool
 10  Amount              66863 non-null  float64
dtypes: bool(2), float64(1), int64(4), object(4)
memory usage: 4.7+ MB

In [467]:
ts1.columns

Index(['WorkstationGroupID', 'TranID', 'BeginDateTime', 'EndDateTime',
       'OperatorID', 'TranTime', 'BreakTime', 'ArtNum', 'TNcash', 'TNcard',
       'Amount'],
      dtype='object')

In [ ]:
ts1.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,66863.000000,66863.000000,66863.000000,66863.000000,66863.000000,66863.0
mean,176.595576,73.700432,42.844623,14.343703,75.611827,1.0
std,91.730739,64.351228,76.625655,14.895184,94.571673,0.0
min,101.000000,1.000000,2.000000,1.000000,0.080000,1.0
25%,116.000000,31.000000,11.000000,5.000000,21.680000,1.0
50%,131.000000,56.000000,19.000000,10.000000,47.480000,1.0
75%,265.000000,95.000000,39.000000,19.000000,96.250000,1.0
max,606.000000,983.000000,1199.000000,221.000000,6883.500000,1.0

In [ ]:
ts1[~ts1['TNcash'] & ~ts1['TNcard']] # ใช้ coupon

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
45,1,171207106022532,2017-12-07T15:26:02,2017-12-07T15:27:15,101,73,19,33,False,False,125.89,1
65,1,171207106022563,2017-12-07T15:48:05,2017-12-07T15:49:35,101,90,16,29,False,False,118.33,1
77,1,171207106022580,2017-12-07T16:02:17,2017-12-07T16:02:38,101,21,18,7,False,False,22.87,1
298,1,17120810605344,2017-12-08T14:44:31,2017-12-08T14:45:10,101,39,324,5,False,False,39.34,1
338,1,17120810605406,2017-12-08T15:32:15,2017-12-08T15:32:52,101,37,10,12,False,False,46.42,1
...,...,...,...,...,...,...,...,...,...,...,...,...
66175,1,17121810607524,2017-12-18T18:11:27,2017-12-18T18:13:49,605,142,16,58,False,False,233.01,1
66187,1,17121810607542,2017-12-18T18:24:41,2017-12-18T18:25:19,605,38,8,7,False,False,30.01,1
66226,1,17121810607606,2017-12-18T19:09:43,2017-12-18T19:10:15,605,32,10,8,False,False,16.79,1
66392,1,17121910607658,2017-12-19T19:49:35,2017-12-19T19:51:04,605,89,9,51,False,False,275.15,1
66418,1,1712071060813,2017-12-07T10:13:17,2017-12-07T10:13:28,606,11,11,1,False,False,7.17,1

In [ ]:
ts2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47066 entries, 0 to 47065
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  47066 non-null  object
 1   TranID              47066 non-null  object
 2   BeginDateTime       47066 non-null  object
 3   EndDateTime         47066 non-null  object
 4   OperatorID          47066 non-null  int64
 5   TranTime            47066 non-null  int64
 6   BreakTime           47066 non-null  int64
 7   ArtNum              47066 non-null  int64
 8   TNcash              47066 non-null  bool
 9   TNcard              47066 non-null  bool
 10  Amount              47066 non-null  float64
 11  Period              47066 non-null  int64
dtypes: bool(2), float64(1), int64(5), object(4)
memory usage: 3.7+ MB

In [ ]:
ts2.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,47066.000000,47066.000000,47066.000000,47066.000000,47066.000000,47066.0
mean,226.645094,71.053393,42.024604,15.804020,68.645274,2.0
std,110.838012,57.781746,73.445125,16.380067,77.816865,0.0
min,10.000000,0.000000,-12.000000,1.000000,0.000000,2.0
25%,114.000000,32.000000,14.000000,5.000000,20.082500,2.0
50%,267.000000,56.000000,21.000000,11.000000,43.720000,2.0
75%,328.000000,93.000000,40.000000,21.000000,88.790000,2.0
max,606.000000,1137.000000,1189.000000,369.000000,1654.580000,2.0

In [ ]:
ts2[~ts2['TNcash'] & ~ts2['TNcard']] # coupon

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2
90,1,1902141060542,2019-02-14T07:54:58,2019-02-14T07:55:49,101,51,20,23,False,False,97.10,2
388,1,19021510604101,2019-02-15T08:30:33,2019-02-15T08:30:33,101,0,100,4,False,False,43.74,2
877,1,19021810604321,2019-02-18T14:06:49,2019-02-18T14:06:49,101,0,40,7,False,False,40.13,2
1586,1,19022210605281,2019-02-22T12:39:11,2019-02-22T12:39:11,101,0,108,40,False,False,272.29,2
...,...,...,...,...,...,...,...,...,...,...,...,...
46149,1,190215106022635,2019-02-15T18:41:33,2019-02-15T18:44:11,600,158,15,68,False,False,321.27,2
46363,1,19021810606131,2019-02-18T18:23:53,2019-02-18T18:24:07,601,14,7,5,False,False,42.51,2
46602,1,19022410607311,2019-02-24T16:55:43,2019-02-24T16:57:02,603,79,45,44,False,False,145.95,2
46644,1,190224106013139,2019-02-24T18:25:24,2019-02-24T18:25:24,603,0,155,80,False,False,282.63,2
47004,1,19022310606384,2019-02-23T17:04:38,2019-02-23T17:06:19,606,101,13,40,False,False,280.31,2

In [ ]:
ts2.loc[20370:20375]

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
20370,1,1902231060891,2019-02-23T11:07:13,2019-02-23T11:10:05,143,172,9,62,False,True,252.95,2
20371,1,1902231060893,2019-02-23T11:10:14,2019-02-23T11:11:41,143,87,8,38,False,True,88.79,2
20372,1,1902231060895,2019-02-23T11:11:49,2019-02-23T11:13:08,143,79,-12,19,False,True,60.47,2
20373,1,19022310607118,2019-02-23T11:12:56,2019-02-23T11:12:56,143,0,51,62,False,False,95.79,2
20374,1,19022310607120,2019-02-23T11:13:47,2019-02-23T11:14:17,143,30,7,3,False,True,65.29,2
20375,1,19022310607122,2019-02-23T11:14:24,2019-02-23T11:15:08,143,44,13,10,True,False,47.42,2

In [ ]:
ts3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49340 entries, 0 to 49339
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   WorkstationGroupID  49340 non-null  object
 1   TranID              49340 non-null  object
 2   BeginDateTime       49340 non-null  object
 3   EndDateTime         49340 non-null  object
 4   OperatorID          49340 non-null  int64
 5   TranTime            49340 non-null  int64
 6   BreakTime           49340 non-null  int64
 7   ArtNum              49340 non-null  int64
 8   TNcash              49340 non-null  bool
 9   TNcard              49340 non-null  bool
 10  Amount              49340 non-null  float64
 11  Period              49340 non-null  int64
dtypes: bool(2), float64(1), int64(5), object(4)
memory usage: 3.9+ MB

In [ ]:
ts3.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,49340.000000,49340.000000,49340.000000,49340.000000,49340.000000,49340.0
mean,189.438468,68.059972,41.272821,16.871463,72.394871,3.0
std,106.103554,57.888295,65.739459,18.152183,84.605779,0.0
min,10.000000,0.000000,1.000000,1.000000,-3.440000,3.0
25%,114.000000,30.000000,16.000000,5.000000,20.980000,3.0
50%,131.000000,52.000000,23.000000,11.000000,46.015000,3.0
75%,268.000000,88.000000,41.000000,22.000000,93.052500,3.0
max,606.000000,994.000000,1199.000000,500.000000,4199.160000,3.0

In [ ]:
ts3

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19040310601356,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,3
1,1,19032910607385,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,3
2,1,19032910607386,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,3
3,1,19032910607387,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,3
4,1,19032910607389,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,3
...,...,...,...,...,...,...,...,...,...,...,...,...
49335,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
49336,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3
49337,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
49338,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
49339,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

#ใส่ ช่วงเวลาของการขาย

In [468]:
ts1['Period'] = 1
ts2['Period'] = 2
ts3['Period'] = 3
op1['Period'] = 1
op2['Period'] = 2
op3['Period'] = 3

In [473]:
ts2[ts2['BreakTime'] <= 0]

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
20372,1,1902231060895,2019-02-23T11:11:49,2019-02-23T11:13:08,143,79,-12,19,False,True,60.47,2

# Cleaning ข้อมูล

In [474]:
ts2_clean = ts2.copy()

In [475]:
ts2_clean = ts2_clean[ts2_clean['BreakTime'] >= 0]
ts2_clean

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19022310606223,2019-02-23T14:35:12,2019-02-23T14:35:12,10,0,2,1,False,False,1.79,2
1,1,190213106054,2019-02-13T07:50:14,2019-02-13T07:50:23,101,9,17,3,True,False,13.19,2
2,1,190213106055,2019-02-13T07:50:40,2019-02-13T07:51:01,101,21,209,6,True,False,21.20,2
3,1,190213106058,2019-02-13T07:54:30,2019-02-13T07:55:05,101,35,16,1,True,False,106.20,2
4,1,190213106059,2019-02-13T07:55:21,2019-02-13T07:55:27,101,6,17,1,True,False,106.20,2
...,...,...,...,...,...,...,...,...,...,...,...,...
47061,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.45,2
47062,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.97,2
47063,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.34,2
47064,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.42,2
47065,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2

In [476]:
ts2_clean.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,47065.000000,47065.000000,47065.000000,47065.000000,47065.000000,47065.0
mean,226.646871,71.053224,42.025752,15.803952,68.645448,2.0
std,110.838519,57.782348,73.445483,16.380235,77.817682,0.0
min,10.000000,0.000000,2.000000,1.000000,0.000000,2.0
25%,114.000000,32.000000,14.000000,5.000000,20.080000,2.0
50%,267.000000,56.000000,21.000000,11.000000,43.720000,2.0
75%,328.000000,93.000000,40.000000,21.000000,88.790000,2.0
max,606.000000,1137.000000,1189.000000,369.000000,1654.580000,2.0

In [479]:
import numpy as np

In [484]:
ts3[ts3['Amount'] <= 0]

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
22773,1,1.904081e+13,2019-04-08T11:42:49,2019-04-08T11:42:49,128,0,177,1,False,False,0.00,3
22774,1,1.904081e+13,2019-04-08T11:45:46,2019-04-08T11:46:32,128,46,14,1,False,False,0.00,3
32913,8,1.904041e+14,2019-04-04T12:58:28,2019-04-04T12:58:28,267,0,68,2,False,False,0.00,3
33708,8,1.904081e+14,2019-04-08T11:14:32,2019-04-08T11:14:32,267,0,98,2,False,False,0.00,3
33719,8,1.904081e+14,2019-04-08T11:55:04,2019-04-08T11:55:04,267,0,1156,1,False,False,0.00,3
37947,8,1.904101e+14,2019-04-10T11:04:34,2019-04-10T11:04:45,268,11,108,1,False,False,-3.44,3
38826,8,1.903301e+13,2019-03-30T08:48:40,2019-03-30T08:48:40,269,0,80,2,False,False,0.00,3
39790,8,1.904021e+14,2019-04-02T14:34:35,2019-04-02T14:34:45,269,10,49,1,False,False,-0.25,3
40906,8,1.904061e+14,2019-04-06T10:26:49,2019-04-06T10:27:01,269,12,22,1,False,False,-2.51,3
41892,8,1.904101e+14,2019-04-10T13:24:46,2019-04-10T13:24:46,269,0,50,2,False,False,0.00,3

In [485]:
ts3_no_minus = ts3.copy()
ts3_no_minus

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19040310601356,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,3
1,1,19032910607385,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,3
2,1,19032910607386,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,3
3,1,19032910607387,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,3
4,1,19032910607389,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,3
...,...,...,...,...,...,...,...,...,...,...,...,...
49335,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
49336,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3
49337,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
49338,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
49339,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

In [486]:
ts3_no_minus = ts3_no_minus[ts3_no_minus['Amount'] >= 0]
ts3_no_minus

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19040310601356,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,3
1,1,19032910607385,2019-03-29T14:04:50,2019-03-29T14:05:31,101,41,21,6,True,False,13.74,3
2,1,19032910607386,2019-03-29T14:05:52,2019-03-29T14:06:35,101,43,44,12,True,False,97.47,3
3,1,19032910607387,2019-03-29T14:07:19,2019-03-29T14:07:43,101,24,25,6,False,True,37.18,3
4,1,19032910607389,2019-03-29T14:08:08,2019-03-29T14:09:44,101,96,18,48,True,False,154.70,3
...,...,...,...,...,...,...,...,...,...,...,...,...
49335,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
49336,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3
49337,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
49338,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
49339,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

In [487]:
ts3_no_minus.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,49337.000000,49337.000000,49337.000000,49337.000000,49337.000000,49337.0
mean,189.433650,68.063441,41.271703,16.872428,72.399399,3.0
std,106.104981,57.888345,65.740705,18.152313,84.606358,0.0
min,10.000000,0.000000,1.000000,1.000000,0.000000,3.0
25%,114.000000,30.000000,16.000000,5.000000,20.990000,3.0
50%,131.000000,52.000000,23.000000,11.000000,46.020000,3.0
75%,268.000000,88.000000,41.000000,22.000000,93.060000,3.0
max,606.000000,994.000000,1199.000000,500.000000,4199.160000,3.0

In [488]:
ts3_clean = ts3_no_minus.copy()

In [490]:
ts3[ts3['TranTime'] <= 0]

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,19040310601356,2019-04-03T13:28:17,2019-04-03T13:28:17,10,0,1,1,False,False,11.99,3
5,1,19032910607390,2019-03-29T14:10:02,2019-03-29T14:10:02,101,0,270,22,False,False,108.06,3
371,1,19033010607409,2019-03-30T15:39:29,2019-03-30T15:39:29,101,0,118,39,False,False,192.03,3
1113,1,19040510604222,2019-04-05T10:11:30,2019-04-05T10:11:30,101,0,289,83,False,False,434.53,3
1901,1,19041010604121,2019-04-10T08:52:16,2019-04-10T08:52:16,101,0,129,22,False,False,283.81,3
...,...,...,...,...,...,...,...,...,...,...,...,...
46933,1,190403106087,2019-04-03T15:01:54,2019-04-03T15:01:54,346,0,777,1,False,False,1.69,3
47159,1,1.904041e+13,2019-04-04T19:31:39,2019-04-04T19:31:39,346,0,46,3,False,False,2.39,3
47165,1,1.904041e+13,2019-04-04T19:37:08,2019-04-04T19:37:08,346,0,71,16,False,False,87.76,3
48511,1,1.903301e+13,2019-03-30T11:15:44,2019-03-30T11:15:44,603,0,104,10,False,False,74.65,3
48528,1,1.903301e+13,2019-03-30T11:43:56,2019-03-30T11:43:56,603,0,61,9,False,False,27.42,3

# ต่อตาราง Operator

In [491]:
op_con1 = pd.concat([op1, op2], ignore_index=True)
op_con1

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items,Period
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn,1
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn,1
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn,1
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn,1
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn,1
...,...,...,...,...,...,...,...
9921,1,12,190226106012628,2019-02-26T21:44:52,332,OperatorUnLock,2
9922,1,20,190226106020667,2019-02-26T21:53:12,131,OperatorSignOff,2
9923,1,12,190226106012644,2019-02-26T22:00:49,332,OperatorLock,2
9924,1,12,190226106012645,2019-02-26T22:01:48,332,OperatorUnLock,2
9925,1,12,190226106012648,2019-02-26T22:03:46,332,OperatorSignOff,2

In [492]:
op_con2 = pd.concat([op_con1, op3], ignore_index=True)
op_con2

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items,Period
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn,1
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn,1
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn,1
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn,1
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn,1
...,...,...,...,...,...,...,...
14099,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff,3
14100,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff,3
14101,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn,3
14102,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff,3
14103,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff,3

# ดำเนินการเกี่ยวกับ Operator ไฟล์

In [519]:
op_process = op_con2.copy()

In [520]:
op_process.describe()

             Period
count  14104.000000
mean       1.962422
std        0.792885
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        3.000000

In [523]:
op_date = op_process['BeginDateTime'].str.split('T')
op_date

0        [2017-12-07, 06:04:01]
1        [2017-12-07, 06:04:15]
2        [2017-12-07, 06:05:36]
3        [2017-12-07, 06:05:41]
4        [2017-12-07, 06:05:56]
                  ...
14099    [2019-04-10, 21:53:58]
14100    [2019-04-10, 21:54:30]
14101    [2019-04-10, 21:55:05]
14102    [2019-04-10, 22:00:25]
14103    [2019-04-10, 22:10:57]
Name: BeginDateTime, Length: 14104, dtype: object

In [525]:
op_process['Date'] = [i[0] for i in op_date]
op_process

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items,Period,Date
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn,1,2017-12-07
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn,1,2017-12-07
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn,1,2017-12-07
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn,1,2017-12-07
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn,1,2017-12-07
...,...,...,...,...,...,...,...,...
14099,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff,3,2019-04-10
14100,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff,3,2019-04-10
14101,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn,3,2019-04-10
14102,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff,3,2019-04-10
14103,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff,3,2019-04-10

#Sent out file Operator

In [493]:
op_con2.to_csv('operator.csv', index=False)

# ต่อตาราง Transaction

In [494]:
ts_con = pd.concat([ts1, ts2_clean], ignore_index=True)
ts_con

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1
...,...,...,...,...,...,...,...,...,...,...,...,...
113923,1,19022310606490,2019-02-23T19:39:47,2019-02-23T19:40:21,606,34,38,8,False,True,26.45,2
113924,1,19022310606494,2019-02-23T19:40:59,2019-02-23T19:41:18,606,19,11,3,False,True,14.97,2
113925,1,19022310606496,2019-02-23T19:41:29,2019-02-23T19:41:56,606,27,36,6,False,True,55.34,2
113926,1,19022310606499,2019-02-23T19:42:32,2019-02-23T19:42:57,606,25,22,11,True,False,47.42,2
113927,1,19022310606500,2019-02-23T19:43:19,2019-02-23T19:44:20,606,61,18,13,True,False,129.38,2

In [495]:
ts_con2 = pd.concat([ts_con, ts3_clean], ignore_index=True)
ts_con2

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1
...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

In [496]:
ts_con2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163265 entries, 0 to 163264
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   WorkstationGroupID  163265 non-null  object
 1   TranID              163265 non-null  object
 2   BeginDateTime       163265 non-null  object
 3   EndDateTime         163265 non-null  object
 4   OperatorID          163265 non-null  int64
 5   TranTime            163265 non-null  int64
 6   BreakTime           163265 non-null  int64
 7   ArtNum              163265 non-null  int64
 8   TNcash              163265 non-null  bool
 9   TNcard              163265 non-null  bool
 10  Amount              163265 non-null  float64
 11  Period              163265 non-null  int64
dtypes: bool(2), float64(1), int64(5), object(4)
memory usage: 12.8+ MB

#add Payment Label

In [499]:
ts_con_process = ts_con2.copy()
ts_con_process

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1
...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

In [500]:
ts_con_process.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 163265 entries, 0 to 163264
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   WorkstationGroupID  163265 non-null  object
 1   TranID              163265 non-null  object
 2   BeginDateTime       163265 non-null  object
 3   EndDateTime         163265 non-null  object
 4   OperatorID          163265 non-null  int64
 5   TranTime            163265 non-null  int64
 6   BreakTime           163265 non-null  int64
 7   ArtNum              163265 non-null  int64
 8   TNcash              163265 non-null  bool
 9   TNcard              163265 non-null  bool
 10  Amount              163265 non-null  float64
 11  Period              163265 non-null  int64
dtypes: bool(2), float64(1), int64(5), object(4)
memory usage: 12.8+ MB

In [501]:
ts_cash =  ts_con_process[ts_con_process['TNcash'] & ~ts_con_process['TNcard']]
ts_cash

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1
...,...,...,...,...,...,...,...,...,...,...,...,...
163259,1,1.904101e+14,2019-04-10T14:04:02,2019-04-10T14:04:24,606,22,56,17,True,False,45.64,3
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3

In [502]:
ts_card = ts_con_process[~ts_con_process['TNcash'] & ts_con_process['TNcard']]
ts_card

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
5,1,171207106022469,2017-12-07T14:31:03,2017-12-07T14:32:01,101,58,24,12,False,True,232.89,1
9,1,171207106022474,2017-12-07T14:38:21,2017-12-07T14:39:12,101,51,9,15,False,True,42.73,1
10,1,171207106022476,2017-12-07T14:39:21,2017-12-07T14:39:59,101,38,20,8,False,True,81.42,1
11,1,171207106022478,2017-12-07T14:40:19,2017-12-07T14:41:35,101,76,15,19,False,True,108.98,1
15,1,171207106022483,2017-12-07T14:44:16,2017-12-07T14:45:50,101,94,7,25,False,True,83.89,1
...,...,...,...,...,...,...,...,...,...,...,...,...
163243,1,1.904101e+14,2019-04-10T13:42:22,2019-04-10T13:42:44,606,22,11,10,False,True,13.90,3
163245,1,1.904101e+14,2019-04-10T13:43:55,2019-04-10T13:45:07,606,72,29,27,False,True,189.02,3
163246,1,1.904101e+14,2019-04-10T13:45:36,2019-04-10T13:46:10,606,34,19,6,False,True,110.44,3
163255,1,1.904101e+14,2019-04-10T14:00:10,2019-04-10T14:00:58,606,48,19,13,False,True,90.95,3
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3

In [503]:
ts_coupon = ts_con_process[~ts_con_process['TNcash'] & ~ts_con_process['TNcard']]

In [504]:
ts_cashCard = ts_con_process[ts_con_process['TNcash'] & ts_con_process['TNcard']]
ts_cashCard

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period
1304,1,171214106022603,2017-12-14T17:43:02,2017-12-14T17:45:41,101,159,28,36,True,True,129.53,1
1484,1,171216106013393,2017-12-16T17:14:42,2017-12-16T17:15:31,101,49,8,13,True,True,39.80,1
1671,1,171218106022108,2017-12-18T09:25:17,2017-12-18T09:27:14,101,117,10,29,True,True,268.45,1
2270,1,171208106012654,2017-12-08T18:39:36,2017-12-08T18:42:56,104,200,13,48,True,True,348.85,1
2405,1,171208106012899,2017-12-08T21:39:51,2017-12-08T21:43:09,104,198,10,58,True,True,278.38,1
...,...,...,...,...,...,...,...,...,...,...,...,...
162291,1,1.903281e+13,2019-03-28T10:12:22,2019-03-28T10:13:19,603,57,13,14,True,True,32.72,3
162748,1,1.903291e+12,2019-03-29T18:19:38,2019-03-29T18:21:44,606,126,12,11,True,True,68.15,3
162793,1,1.903311e+13,2019-03-31T18:10:40,2019-03-31T18:14:31,606,231,39,97,True,True,529.18,3
162908,1,1.904061e+13,2019-04-06T14:11:57,2019-04-06T14:14:00,606,123,21,51,True,True,191.23,3
162960,1,1.904061e+13,2019-04-06T16:52:54,2019-04-06T16:55:51,606,177,20,81,True,True,288.68,3

In [505]:
coupon_index = ts_coupon.index
coupon_index

Int64Index([    45,     65,     77,    298,    338,    392,    637,    703,
               757,    781,
            ...
            162436, 162437, 162453, 162463, 162883, 162903, 162904, 162987,
            163031, 163085],
           dtype='int64', length=1241)

In [506]:
cash_index = ts_cash.index
cash_index

Int64Index([     0,      1,      2,      3,      4,      6,      7,      8,
                12,     13,
            ...
            163253, 163254, 163256, 163257, 163258, 163259, 163260, 163262,
            163263, 163264],
           dtype='int64', length=83779)

In [507]:
card_index = ts_card.index
card_index

Int64Index([     5,      9,     10,     11,     15,     16,     17,     20,
                25,     26,
            ...
            163234, 163236, 163237, 163238, 163242, 163243, 163245, 163246,
            163255, 163261],
           dtype='int64', length=77537)

In [508]:
cashCard_index = ts_cashCard.index
cashCard_index

Int64Index([  1304,   1484,   1671,   2270,   2405,   2613,   3640,   3732,
              4145,   4304,
            ...
            161199, 161329, 161724, 161769, 161976, 162291, 162748, 162793,
            162908, 162960],
           dtype='int64', length=708)

In [509]:
ts_con_process['Payment'] = [' '] * len(ts_con_process)
ts_con_process

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period,Payment
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3,
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3,
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3,
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3,
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3,

## ใส่ Label การจ่าย

In [510]:
ts_con_process.loc[coupon_index, 'Payment'] = 'coupon'
ts_con_process.loc[cash_index, 'Payment'] = 'cash'
ts_con_process.loc[card_index, 'Payment'] = 'card'
ts_con_process.loc[cashCard_index, 'Payment'] = 'cash-card'

In [511]:
ts_con_process

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period,Payment
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,cash
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,cash
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,cash
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,cash
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3,cash
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3,card
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3,cash
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3,cash
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3,cash

In [512]:
ts_con_process[ts_con_process['Payment'] == 'coupon']

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period,Payment
45,1,171207106022532,2017-12-07T15:26:02,2017-12-07T15:27:15,101,73,19,33,False,False,125.89,1,coupon
65,1,171207106022563,2017-12-07T15:48:05,2017-12-07T15:49:35,101,90,16,29,False,False,118.33,1,coupon
77,1,171207106022580,2017-12-07T16:02:17,2017-12-07T16:02:38,101,21,18,7,False,False,22.87,1,coupon
298,1,17120810605344,2017-12-08T14:44:31,2017-12-08T14:45:10,101,39,324,5,False,False,39.34,1,coupon
338,1,17120810605406,2017-12-08T15:32:15,2017-12-08T15:32:52,101,37,10,12,False,False,46.42,1,coupon
...,...,...,...,...,...,...,...,...,...,...,...,...,...
162903,1,1.904061e+13,2019-04-06T14:03:35,2019-04-06T14:03:47,606,12,9,2,False,False,23.41,3,coupon
162904,1,1.904061e+13,2019-04-06T14:03:56,2019-04-06T14:04:23,606,27,12,7,False,False,39.20,3,coupon
162987,1,1.904061e+13,2019-04-06T17:35:28,2019-04-06T17:36:00,606,32,13,12,False,False,75.95,3,coupon
163031,1,1.904061e+13,2019-04-06T19:45:55,2019-04-06T19:46:38,606,43,27,21,False,False,68.07,3,coupon
163085,1,1.904061e+13,2019-04-06T20:48:43,2019-04-06T20:50:03,606,80,7,57,False,False,178.57,3,coupon

In [513]:
ts_con_process.to_csv('transactions_with_Payment.csv', index=False)

In [514]:
ts_con_time = ts_con_process.copy()
ts_con_time

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period,Payment
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,cash
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,cash
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,cash
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,cash
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,cash
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3,cash
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3,card
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3,cash
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3,cash
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3,cash

In [515]:
ts_con_time[['date', 'time']] = (ts_con_time.['BeginDateTime'].str.split('T', n=1, expand = True))
ts_con_time

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Period,Payment,date,time
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71,1,cash,2017-12-07,14:23:23
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76,1,cash,2017-12-07,14:25:09
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77,1,cash,2017-12-07,14:27:28
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88,1,cash,2017-12-07,14:28:04
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34,1,cash,2017-12-07,14:29:40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163260,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14,3,cash,2019-04-10,14:05:20
163261,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90,3,card,2019-04-10,14:06:39
163262,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99,3,cash,2019-04-10,14:07:51
163263,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88,3,cash,2019-04-10,14:09:46
163264,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33,3,cash,2019-04-10,14:10:29

# sent out Transactions file

In [521]:
ts_con_time.describe()

,OperatorID,TranTime,BreakTime,ArtNum,Amount,Period
count,163265.000000,163265.000000,163265.000000,163265.000000,163265.000000,163265.000000
mean,194.903580,71.233871,42.133243,15.528809,72.632841,1.892653
std,104.049699,60.634667,72.567176,16.398854,87.061886,0.836784
min,10.000000,0.000000,1.000000,1.000000,0.000000,1.000000
25%,114.000000,31.000000,13.000000,5.000000,20.990000,1.000000
50%,132.000000,55.000000,21.000000,10.000000,45.910000,2.000000
75%,268.000000,92.000000,40.000000,20.000000,93.110000,3.000000
max,606.000000,1137.000000,1199.000000,500.000000,6883.500000,3.000000

In [517]:
ts_con_time.to_csv('transactions_with_Time.csv', index=False)

In [518]:
ts_con2.to_csv('transactions.csv', index=False)